datasources.default.username=root
datasources.default.password=aluno
datasources.default.db-type=mysql
datasources.default.dialect=MYSQL
micronaut.application.name=micronaut-rest
datasources.default.schema-generate=CREATE_DROP
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.url=jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true

application.max=50